parameters:
    limit_objs_bytag:          10             # ByTag Pager limit.   (Default 10)
    limit_objs_search:         10             # Search Pager limit.  (Default 10)
    limit_objs_mostviewed:     5             # Mostviewed limit.     (Default 3)
    limit_objs_recentlyadded:  5             # Recentlyadded limit.    (Default 3)
    columns_objs_bytag:        2             # Number of columns for bytag.  (Default 2)
    columns_objs_search:       2             # Number of columns for search. (Default 2)
    columns_objs_announces:    2             # Number of columns for announces. (Default 1)
    columns_objs_catalogue:    2             # Number of columns for full catalogue. (Default 1)
    catalogue_thumbnails:      true          # If set to true, the full catalogue will list thumbnails instead of text.
    menu_stats:                false          # To show stats on the menu or not. (Default true)
    categories_tag_cod:        ITUNESU       # Cod of Root Tag to create the Categories page.
    categories.list_general_tags:  true        # If true, adds a 'general tag' to each category.
    pumukit_web_tv.breadcrumbs_home_title:  'OER Portal'
    search.parent_tag.cod: ITUNESU
